import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';

import LayoutCare from '../components/LayoutCare';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>GO - Test PDF Generation</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
      <h2>Generación de documentos PDF del GO</h2>
        <div className={styles.description}>
          <p>Select the document you want to generate:&nbsp;</p>
          <div>
            <a
              href='http://172.18.88.4:4204/productos/Dearrollo'
              target='_blank'
              rel='noopener noreferrer'
            >
              <Image
                src='/logoGOw.png'
                alt='Vercel Logo'
                className={styles.vercelLogo}
                width={75}
                height={75}
                priority
              />
            </a>
          </div>
        </div>
        <div>
          <LayoutCare></LayoutCare>
        </div>
        <div className={styles.center}>
          <Image
            className={styles.logo}
            src='/next.svg'
            alt='Next.js Logo'
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src='/thirteen.svg'
              alt='13'
              width={40}
              height={31}
              priority
            />
          </div>
        </div>
      </main>
    </>
  );
}
